version: 2.1

orbs:
  go: circleci/go@1.6.0

jobs:
  docker-cache:
    resource_class: 2xlarge
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pachd-docker-{{ checksum "etc/testing/docker-cache.sh" }}
            - v1-pachd-docker
      - run: |
          etc/testing/docker-cache.sh
      - save_cache:
          paths:
            - /tmp/docker-cache 
          key: v1-pachd-docker-{{ checksum "etc/testing/docker-cache.sh" }}

  test:
    parameters:
      bucket:
        type: string
    resource_class: 2xlarge
    machine:
      image: ubuntu-2004:202101-01
    environment:
      PPS_BUCKETS: "4"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - restore_cache:
          keys:
            - v1-pachd-docker-{{ checksum "etc/testing/docker-cache.sh" }}
            - v1-pachd-docker
      - run: etc/testing/travis_install.sh 
      - run: etc/testing/travis.sh 

workflows:
  all-tests:
    jobs:
      - docker-cache
      - test:
          requires:
            - docker-cache
          matrix:
            parameters:
              bucket:
              - MISC
              # If you want to update the number of PPS buckets, you'll neet to
              # update the value of PPS_BUCKETS above
              - ADMIN
              - AUTH
              - ENTERPRISE
              - PFS
              - PPS1
              - PPS2
              - PPS3
              - PPS4
              - EXAMPLES
              - OBJECT
