version: 2.1

orbs:
  go: circleci/go@1.6.0

jobs:
  build:
    resource_class: 2xlarge
    docker:
    - image: circleci/golang:1.15
      auth:
          username: pachydermbuildbot
          password: $DOCKER_PWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: |
          wget -nv -O - https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - run: |
          PATH=./bin/:$PATH etc/testing/travis_build.sh 
      

  test:
    parameters:
      bucket:
        type: string
    resource_class: 2xlarge
    machine:
      image: ubuntu-2004:202101-01
    environment:
      PPS_BUCKETS: "4"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: etc/testing/travis_install.sh 
      - run: etc/testing/travis.sh 

workflows:
  all-tests:
    jobs:
      - build
      - test:
          requires:
            - build
          matrix:
            parameters:
              bucket:
              - MISC
              # If you want to update the number of PPS buckets, you'll neet to
              # update the value of PPS_BUCKETS above
              - ADMIN
              - AUTH
              - ENTERPRISE
              - PFS
              - PPS1
              - PPS2
              - PPS3
              - PPS4
              - EXAMPLES
              - OBJECT
